server:
  port: 9188

hystrix:
  #threadpool.default.coreSize: 50
  #threadpool.HystrixThreadPoolKey.coreSize: 50
  command:
    fetchService:
      #circuit will trip when this limit is reached
      requestVolumeThreshold: 60
      #this will ensure when the circuit trips, the circuit remains open for this time
      sleepWindowInMilliseconds: 100
      #when the number of failures of calling the service is greater than the below percentage
      errorThresholdPercentage: 90
      #failure can be anything, exception, response timeout, this timeouts the thread
      execution.isolation.thread.timeoutInMilliseconds: 1000