version: '3'
services:
  mycassandra:
    image: cassandra
    container_name: mycassandra
    ports:
      - "9042:9042"
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "kafka-topic:1:3"
#  redis:
#    container_name: myredis
#    image: redis
#    ports:
#      - "6379:6379"

#run docker compose from intellij terminal
#docker-compose up -d
#docker-compose start
#docker-compose stop

#list of containers
#docker ps -a

#list of active containers
#docker ps

#to run the docker container
#docker exec -it <container id> bash

#cassandra
# after running cassandra container type cqlsh, and start using the database