server:
  port: 8888

spring:
  application:
    name: springboot-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gopikrishhnaChokkalamani/configuration-repository.git
          search-paths:
          - configuration/springboot-actuator/
          - configuration/

