server:
  port: 9197

spring:
  application:
    name: springbot-ehcache-cachemanager
  data:
    cassandra:
      port: 9042
      contact-points: localhost
      local-datacenter: datacenter1
      keyspace-name: mykeyspace