server:
  port: 9208

spring:
  application:
    name: springboot-actuator
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888

#if you want to have a customized uri, instead of the default /actuator
management:
  endpoints:
    web:
      base-path: /myapp/actuator
#expose all endpoints
      exposure:
        include: "*"
#enable endpoints by comma seperation
#       include: health, beans, env
#if you want a specific endpoint to be enabled
  endpoint:
    health:
      enabled: true
    refresh:
      enabled: true

logging:
  level:
    root: ERROR
#if you want a specific package to run on a different level
    com.springboot: TRACE
#this is also possible - check the loggers actuator endpoint to understand better
#    com.springboot.ActuatorController