server:
  port: 9198

spring:
  application:
    name: springboot-feign-client
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

employee:
  profiles:
    host:
      uri: http://localhost:9193