server:
  port: 9191
spring:
  application:
    name: springboot-cassandra
  data:
    cassandra:
      port: 9042
      contact-points: localhost
      local-datacenter: datacenter1
      keyspace-name: mykeyspace