server:
  port: 9203

spring:
  application:
    name: springboot-security-basic-auth

basic:
  app:
    security:
      user-name: user
      password: $2a$04$dSIz4rdSaWWYZ9nooLXEKewSUY3yM5UGMaQN2c6ZjEqwXund0pa1m
      role: USER