//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.07 at 11:41:31 AM EDT 
//


package com.springboot.wsdl.schema.student;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for major.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="major"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MATHS"/&gt;
 *     &lt;enumeration value="CHEMISTRY"/&gt;
 *     &lt;enumeration value="PHYSICS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "major")
@XmlEnum
public enum Major {

    MATHS,
    CHEMISTRY,
    PHYSICS;

    public String value() {
        return name();
    }

    public static Major fromValue(String v) {
        return valueOf(v);
    }

}
