server:
  port: 9206

spring:
  application:
    name: springboot-security-oauth2
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true

security:
  oauth2:
    resource:
      filter-order: 3